# -----------------------------------------------------------------------------
# Yummo site base properties
# -----------------------------------------------------------------------------
# A snazzy title for your site
title: Yummo, a tasty wittle theme
# The site tag
tag_text: Yummo
# The overall description of your Yummo site
description: A tasty wittle theme
# Yummo site author
author: Corbs
# Yummo site author's email
email: corbs@retro.io
# The sub-path to hang your Yummo site from, e.g. /blog
baseurl: ""
# The base hostname (w/ protocol) of your Yummo site, e.g. http://corbs.io
url: ""
# -----------------------------------------------------------------------------
# Yummo site feature properties
# -----------------------------------------------------------------------------
# The style to apply (see _sass/yummo/themes)
style: corbs
# The site wide logo
#logo: assets/images/site/logo.svg
# Where the site should grab images from (can be local, e.g. assets/images)
images: https://storage.googleapis.com/corbs-foto/yolo
# The site favicon to use
favicon: "logo.png"

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "../" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

# Build settings
version: v1.0
markdown: kramdown
permalink: /:slug.html
include: ['_pages']
exclude:
  - "README.md"
  - "Makefile"
  - "Containerfile"
  - ".yo-build"
  - "src/"
  - "docs/"
sass:
  style: uncompressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
