# -----------------------------------------------------------------------------
# Jekyll site settings, see _data/settings.yml for Yummo settings
# -----------------------------------------------------------------------------
# baseurl: The sub-path your site is hosted from, for example: /blog
# -----------------------------------------------------------------------------
baseurl: ""
# -----------------------------------------------------------------------------
# url: The protocol and hostname for your site, for example: https://corbs.io
# -----------------------------------------------------------------------------
url: ""
# -----------------------------------------------------------------------------
# The site favicon to use
# -----------------------------------------------------------------------------
favicon: "logo.png"
# -----------------------------------------------------------------------------
# Site post rules
# -----------------------------------------------------------------------------
defaults:
  # samples
  - scope:
      path: "_posts/samples"
      type: posts
    values:
      category: samples
      permalink: samples/:title/
  # weeklies
  - scope:
      path: "_posts/weeklies"
      type: posts
    values:
      category: weekly
      permalink: weeklies/:year/:week/
# -----------------------------------------------------------------------------
# Build settings
# -----------------------------------------------------------------------------
version: v1.1
markdown: kramdown
permalink: /:slug.html
include: ['_pages']
exclude:
  - "README.md"
  - "Makefile"
  - "Containerfile"
  - "src/"
  - "docs/"
  - ".idea/"
  - ".generated"
# -----------------------------------------------------------------------------
# sass_dir: Folder that contains sass/scss files to be processed
# style: compressed or expanded css generation
# -----------------------------------------------------------------------------
sass:
  sass_dir: _sass
  style: expanded
  sourcemap: always