# -----------------------------------------------------------------------------
# Yummo base properties
# -----------------------------------------------------------------------------
# A snazzy title for your site
title: Yummo, a tasty wittle theme
# The site tag
tag_text: Yummo
# The overall description of your Yummo site
description: A tasty wittle theme
# Yummo site author
author: Corbs
# Yummo site author's email
email: corbs@retro.io
# The sub-path to hang your Yummo site from, e.g. /blog
baseurl: ""
# The base hostname (w/ protocol) of your Yummo site, e.g. http://corbs.io
url: ""
# The site favicon to use
favicon: "logo.png"
# -----------------------------------------------------------------------------
# Yummo site properties
# -----------------------------------------------------------------------------
defaults:
  # samples
  - scope:
      path: "_posts/samples"
      type: posts
    values:
      category: samples
      permalink: samples/:title/
  # weeklies
  - scope:
      path: "_posts/weeklies"
      type: posts
    values:
      category: weekly
      permalink: weeklies/:year/:week/
yummo:
  # The style to apply (see _sass/yummo/themes)
  style: corbs
  # Align content, left, center or right (default is left)
  align: left
#  header:
#    logo: assets/images/site/yummo-logo-light.png
#  sidebar:
#    logo: assets/images/logo.png
  # Where the site should grab images from (can be local, e.g. assets/images)
  images: https://storage.googleapis.com/corbs-foto/yolo
  # customize text for homepage link in post layout
  home_link: "<<<"
  # customize how date is formatted
  date_format: "%Y-%m-%d"
  # Is site searchable?
  searchable: false
# -----------------------------------------------------------------------------
# Build settings
# -----------------------------------------------------------------------------
version: v1.1
markdown: kramdown
permalink: /:slug.html
include: ['_pages']
exclude:
  - "README.md"
  - "Makefile"
  - "Containerfile"
  - "src/"
  - "docs/"
  - ".idea/"
  - ".generated"
sass:
  style: uncompressed