# -----------------------------------------------------------------------------
# Yummo site settings. see: _config.yml for jekyll settings
# -----------------------------------------------------------------------------
name: Yummo
version: v1.2
title: Yummo on my friend
description: A tasty wittle theme
author: Corbs
email: corbs@retro.io
brand:
  theme: corbs
  syntax: corbs
align: left
logo: /assets/images/logo.png
# Is site searchable?
searchable: true
search:
  enabled: true
  deep: false
# customize how date is formatted
date_format: "%Y-%m-%d"